services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=118d7cf5e57ffbf2bb8268c867e68334
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_SECRET=118d7cf5e57ffbf2bb8268c867e68335
      - JWT_REFRESH_EXPIRES_IN=7d
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/dist
    ports:
      - "3001:3001"
  platform:
    build:
      context: ./platform
      dockerfile: Dockerfile
    volumes:
      - ./platform:/app
      - /app/node_modules
      - /app/dist
    ports:
      - "3000:3000"
volumes:
  db_data:
